"""init_full

Revision ID: 042b6f6821ea
Revises: 
Create Date: 2026-01-31 20:48:15.366555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '042b6f6821ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS reference")
    op.execute("CREATE SCHEMA IF NOT EXISTS user_data")
    op.create_table('mentors',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='reference'
                    )
    op.create_index(op.f('ix_reference_mentors_name'), 'mentors', [
                    'name'], unique=False, schema='reference')
    op.create_table('skill_levels',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('sort_order', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='reference'
                    )
    op.create_index(op.f('ix_reference_skill_levels_name'), 'skill_levels', [
                    'name'], unique=True, schema='reference')
    op.create_table('teams',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='reference'
                    )
    op.create_index(op.f('ix_reference_teams_name'), 'teams', [
                    'name'], unique=False, schema='reference')
    op.create_table('technologies',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='reference'
                    )
    op.create_index(op.f('ix_reference_technologies_name'), 'technologies', [
                    'name'], unique=False, schema='reference')
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('telegram_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=255), nullable=True),
                    sa.Column('first_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('last_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('team_id', sa.UUID(), nullable=True),
                    sa.Column('skill_level_id', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['skill_level_id'], [
                        'reference.skill_levels.id'], ),
                    sa.ForeignKeyConstraint(
                        ['team_id'], ['reference.teams.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='user_data'
                    )
    op.create_index(op.f('ix_user_data_users_skill_level_id'), 'users', [
                    'skill_level_id'], unique=False, schema='user_data')
    op.create_index(op.f('ix_user_data_users_team_id'), 'users', [
                    'team_id'], unique=False, schema='user_data')
    op.create_index(op.f('ix_user_data_users_telegram_id'), 'users', [
                    'telegram_id'], unique=True, schema='user_data')
    op.create_table('resources',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('uploader_id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=512), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('file_path', sa.String(
                        length=1024), nullable=False),
                    sa.Column('resource_type', sa.Enum('DOC', 'BLUEPRINT',
                                                       'SNIPPET', name='resourcetype'), nullable=False),
                    sa.Column('technology_id', sa.UUID(), nullable=True),
                    sa.Column('mentor_id', sa.UUID(), nullable=True),
                    sa.Column('team_id', sa.UUID(), nullable=True),
                    sa.Column('skill_level_id', sa.UUID(), nullable=True),
                    sa.Column('average_rating', sa.Numeric(
                        precision=3, scale=2), nullable=False),
                    sa.Column('ratings_count', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('meta', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['mentor_id'], ['reference.mentors.id'], ),
                    sa.ForeignKeyConstraint(['skill_level_id'], [
                        'reference.skill_levels.id'], ),
                    sa.ForeignKeyConstraint(
                        ['team_id'], ['reference.teams.id'], ),
                    sa.ForeignKeyConstraint(
                        ['technology_id'], ['reference.technologies.id'], ),
                    sa.ForeignKeyConstraint(
                        ['uploader_id'], ['user_data.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='user_data'
                    )
    op.create_index(op.f('ix_user_data_resources_mentor_id'), 'resources', [
                    'mentor_id'], unique=False, schema='user_data')
    op.create_index(op.f('ix_user_data_resources_resource_type'), 'resources', [
                    'resource_type'], unique=False, schema='user_data')
    op.create_index(op.f('ix_user_data_resources_skill_level_id'), 'resources', [
                    'skill_level_id'], unique=False, schema='user_data')
    op.create_index(op.f('ix_user_data_resources_team_id'), 'resources', [
                    'team_id'], unique=False, schema='user_data')
    op.create_index(op.f('ix_user_data_resources_technology_id'), 'resources', [
                    'technology_id'], unique=False, schema='user_data')
    op.create_index(op.f('ix_user_data_resources_title'), 'resources', [
                    'title'], unique=False, schema='user_data')
    op.create_index(op.f('ix_user_data_resources_uploader_id'), 'resources', [
                    'uploader_id'], unique=False, schema='user_data')
    op.create_table('ratings',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('resource_id', sa.UUID(), nullable=False),
                    sa.Column('score', sa.Integer(), nullable=False),
                    sa.Column('rating_date', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['resource_id'], ['user_data.resources.id'], ),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user_data.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='user_data'
                    )
    op.create_index(op.f('ix_user_data_ratings_resource_id'), 'ratings', [
                    'resource_id'], unique=False, schema='user_data')
    op.create_index(op.f('ix_user_data_ratings_user_id'), 'ratings', [
                    'user_id'], unique=False, schema='user_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_data_ratings_user_id'),
                  table_name='ratings', schema='user_data')
    op.drop_index(op.f('ix_user_data_ratings_resource_id'),
                  table_name='ratings', schema='user_data')
    op.drop_table('ratings', schema='user_data')
    op.drop_index(op.f('ix_user_data_resources_uploader_id'),
                  table_name='resources', schema='user_data')
    op.drop_index(op.f('ix_user_data_resources_title'),
                  table_name='resources', schema='user_data')
    op.drop_index(op.f('ix_user_data_resources_technology_id'),
                  table_name='resources', schema='user_data')
    op.drop_index(op.f('ix_user_data_resources_team_id'),
                  table_name='resources', schema='user_data')
    op.drop_index(op.f('ix_user_data_resources_skill_level_id'),
                  table_name='resources', schema='user_data')
    op.drop_index(op.f('ix_user_data_resources_resource_type'),
                  table_name='resources', schema='user_data')
    op.drop_index(op.f('ix_user_data_resources_mentor_id'),
                  table_name='resources', schema='user_data')
    op.drop_table('resources', schema='user_data')
    op.drop_index(op.f('ix_user_data_users_telegram_id'),
                  table_name='users', schema='user_data')
    op.drop_index(op.f('ix_user_data_users_team_id'),
                  table_name='users', schema='user_data')
    op.drop_index(op.f('ix_user_data_users_skill_level_id'),
                  table_name='users', schema='user_data')
    op.drop_table('users', schema='user_data')
    op.drop_index(op.f('ix_reference_technologies_name'),
                  table_name='technologies', schema='reference')
    op.drop_table('technologies', schema='reference')
    op.drop_index(op.f('ix_reference_teams_name'),
                  table_name='teams', schema='reference')
    op.drop_table('teams', schema='reference')
    op.drop_index(op.f('ix_reference_skill_levels_name'),
                  table_name='skill_levels', schema='reference')
    op.drop_table('skill_levels', schema='reference')
    op.drop_index(op.f('ix_reference_mentors_name'),
                  table_name='mentors', schema='reference')
    op.drop_table('mentors', schema='reference')
    # ### end Alembic commands ###
